bsp: u-boot-fio: imx8mm-lpddr4-evk: fix build error
There is strange issue on u-boot 2022.04+lf-5.15.52-2.1.0-fio:
SET_DFU_ALT_INFO options is enabled due to unknown reason.

Disable the option explicitly to avoid building error [1].

[1]
arch64-none-linux-gnu-ld.bfd: drivers/dfu/dfu.o: in function `dfu_init_env_entities':
drivers/dfu/dfu.c:156: undefined reference to `set_dfu_alt_info'
make: *** [Makefile:1802: u-boot] Error 139

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>