base: distro: mask st-image-bootfs-efi recipe
Mask un-needed st-image-bootfs-efi.bb image recipe. This fixes
build issues of non-stm32mp1 machines:

ERROR: st-image-bootfs-efi.bb: No IMAGE_CMD defined for IMAGE_FSTYPES
entry 'vfat' - possibly invalid type name or missing support class

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>