bsp: dynamic-layers: imx-atf: fix build issue
Fix this build issue on some machines:

| plat/imx/imx8m/gpc_common.c:365:13: error: 'is_secondary_boot'
defined but not used [-Werror=unused-function]

Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>