bsp: lmp-machine-custom: imx7ulpea-ucom: use builtin wireguard
Prefer builtin wireguard module as imx7ulpea now uses kernel 5.10.

The external version of wireguard can't be compiled anymore [1].

[1]
| .../src/compat/compat.h:43:2: error: #error "WireGuard has been merged into Linux >= 5.6 and therefore this compatibility module is no longer required."

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
(cherry picked from commit 8a2e08745e0c246523b5214c259197bcd89ea129)