base: u-boot-fio: add dependency from gnutls-native
U-boot 2022.04 and later require gnutls header files for building
aarch64 machines. Add this dependency to fix a building error [1].

[1]
tools/mkeficapsule.c:21:10: fatal error: gnutls/gnutls.h: No such file or directory
21 | #include <gnutls/gnutls.h>
   |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.host:95: tools/mkeficapsule] Error 1

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>