wireguard: remove upstreamed wg-quick append
Foundries changes on wg-quick landed in meta-openembedded with
commit f36a158aa0b6 ("wireguard-tools: Add a new package for wg-quick")
The bbappend in meta-lmp conflict with this change.

ERROR: wireguard-tools-1.0.20210914-r0 do_package: QA Issue: wireguard-tools-wg-quick is listed in PACKAGES multiple times, this leads to packaging errors. [packages-list]

Removing the bbappend fixes the problem

Signed-off-by: Jerome Brunet <jbrunet@baylibre.com>