bsp: linux-lmp-dev-mfgtool: fix building for linux-ea-v5.10.y
The MAILBOX option is required to avoid getting a linking error [1].

[1]
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x274): undefined reference to `mbox_request_channel_byname'
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x49c): undefined reference to `mbox_request_channel_byname'
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x4e0): undefined reference to `mbox_free_channel'
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x4f8): undefined reference to `mbox_free_channel'
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x53c): undefined reference to `mbox_free_channel'
| arm-lmp-linux-gnueabi-ld.bfd: imx_rpmsg.c:(.text+0x554): undefined reference to `mbox_free_channel'

Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>
Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>