base: wayland: weston-init: require lmp-wayland for files append
When building DISTRO=lmp-[x]wayland several files are setup for
the weston-init recipe.  The files themselves are under an
lmp-wayland directory.

However, the bbappend attempts to use them without qualification.

This results in the following messages whenever any DISTRO besides
lmp-[x]wayland builds weston-init (eventually resulting in a build break):
WARNING: build-xxx/conf/../../layers/openembedded-core/meta/recipes-graphics/wayland/weston-init.bb: Unable to get checksum for weston-init SRC_URI entry utilities-terminal.png: file could not be found
WARNING: build-xxx/conf/../../layers/openembedded-core/meta/recipes-graphics/wayland/weston-init.bb: Unable to get checksum for weston-init SRC_URI entry background.jpg: file could not be found
...
ERROR: weston-init-1.0-r0 do_fetch: Fetcher failure: Unable to find file file://utilities-terminal.png anywhere. The paths that were searched were:

Signed-off-by: Michael Scott <mike@foundries.io>