base: ostree: as we use static linking fix it with clang
glibc is built with gcc and hence encodes some libgcc specific builtins
which are not found when doing static linking with clang using compiler-rt,
so use libgcc to fix floting point emulation undefined reference:

- undefined reference to `__unordtf2'
- undefined reference to `__letf2'

this brings again a3892eb but now only for static linked.

Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>